#
# YAML for ceedling test in module level
#

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :which_ceedling: ../../third-party/ceedling
  :test_file_prefix: test_
  :options_paths: 
    - ../../tools/ceedling

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:test
    - -:test/support
  :source:
    - src/Crc32.c
  :include:
    - inc
    - ../../third-party/rkh/source/portable/test
    - ../../third-party/rkh/source/fwk/inc
    - ../../third-party/rkh/source/trc/inc
    - ../../third-party/rkh/source/sma/inc
    - ../../third-party/rkh/source/sm/inc
    - ../../third-party/rkh/source/queue/inc
    - ../../third-party/rkh/source/mempool/inc
    - ../../third-party/rkh/source/tmr/inc
    - ../tpsens/cbox
    - ../Collector/inc
    - ../BatChr
    - ../GStatus/inc
    - ../ffile/inc
    - ../Config/inc
    - ../gps/inc
    - ../ioChg
    - ../
  :support:
    - test/support

:defines:
  :common: &common_defines [__FFILETEST__, __TEST__]
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :when_no_prototypes: :warn
  :plugins: [ignore_arg, ignore, callback, return_thru_ptr]
  :mock_prefix: Mock_
  :callback_after_arg_check: TRUE
  :when_ptr: :compare_ptr
  :enforce_strict_ordering: TRUE
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:tools_test_linker:
  :arguments:
    - -lm

:tools_test_compiler:
  :arguments:
    - -Wall
    - -Wno-pointer-sign
    - -Wno-missing-braces

:tools_gcov_linker:
  :arguments:
    - -lm

:gcov:
  :html_report_type: detailed

:module_generator:
  :inc_root: inc/

:plugins:
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
